"""Инициализация таблиц

Revision ID: b9bc1f88ae0c
Revises: 
Create Date: 2025-07-16 20:50:37.966111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bc1f88ae0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dino_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dino_class', sa.Text(), nullable=False),
    sa.Column('growth', sa.Integer(), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('thirst', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_dino_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steam_id', sa.Text(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('dino_class', sa.Text(), nullable=False),
    sa.Column('growth', sa.Integer(), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('thirst', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_dino_storage_discord_id'), 'pending_dino_storage', ['discord_id'], unique=False)
    op.create_index(op.f('ix_pending_dino_storage_steam_id'), 'pending_dino_storage', ['steam_id'], unique=False)
    op.create_table('players',
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.Text(), nullable=False),
    sa.Column('tk', sa.Integer(), nullable=False),
    sa.Column('registry_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('discord_id'),
    sa.UniqueConstraint('steam_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_index(op.f('ix_pending_dino_storage_steam_id'), table_name='pending_dino_storage')
    op.drop_index(op.f('ix_pending_dino_storage_discord_id'), table_name='pending_dino_storage')
    op.drop_table('pending_dino_storage')
    op.drop_table('dino_storage')
    # ### end Alembic commands ###
